DEVOPS-1: Написал все нужные файлы для поднятия ELK на docker
archip-io/deployment pull request #4
Opened 2024-03-18 10:36 UTC by antuanviolin

2024-03-18 11:21 UTC, ptrvsrg requested changes

2024-03-18 11:21 UTC, ptrvsrg commented on docker-compose.yml
> +      ELASTIC_USERNAME: ADMIN_NAME
Переменные окружения задаются в формате `${ADMIN_NAME:-default}`, где `default` - значение по умолчанию, если переменная среды не найдена

2024-03-18 11:21 UTC, ptrvsrg commented on docker-compose.yml
> +      - ./configs/elasticsearch/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
`./configs/elasticsearch/config.yml` -> `./elasticsearch/config.yml` вроде директории `configs` нет в корне

И лучше `config.yml` переименовать в `elasticsearch.yml`, так как в контейнере он так должен называться

2024-03-18 11:21 UTC, ptrvsrg commented on docker-compose.yml
> +      - "9200:9200"
Порты договаривались не пробрасывать. Они не нужны для вывода наружу

2024-03-18 11:21 UTC, ptrvsrg commented on docker-compose.yml
> +      - "5044:5044"
Тоже лучше не пробрасыать порты. Они используются только внутри сети `archipio-net`

2024-03-18 11:21 UTC, ptrvsrg commented on docker-compose.yml
> +      - ./configs/logstash/config.yml:/usr/share/logstash/config/logstash.yml:ro
Аналогично, как и у elasticsearch

2024-03-18 11:21 UTC, ptrvsrg commented on docker-compose.yml
> +      - ./docker_volumes/elasticsearch/data:/usr/share/elasticsearch/data
Используй именнованный volume, например, archipio-elasticsearch-data

2024-03-18 11:21 UTC, ptrvsrg commented on docker-compose.yml
> +      - ELK-data:/logstash/pipelines.yml:ELK-data:/logstash/config/pipelines.yml:ro
Мне кажется это так не работает. Попробуй `./logstash/pipelines.yml:/logstash/config/pipelines.yml:ro`

2024-03-18 11:21 UTC, ptrvsrg commented on docker-compose.yml
> +      - ELK-data:/logstash/pipelines:ELK-data:/logstash/config/pipelines:ro
Аналогично с предыдущим

2024-03-18 11:21 UTC, ptrvsrg commented on docker-compose.yml
> +      - ./configs/kibana/config.yml:/usr/share/kibana/config/kibana.yml:ro
Аналогично

2024-03-18 11:21 UTC, ptrvsrg commented on docker-compose.yml
> +    image: elasticsearch:7.16.1
Давай добавим каждому контейнеру имя с префиксом.
`container_name: archipio-elasticsearch`
Имена сервисов оставляй как есть, они будут использоваться для выстраивания зависимостей

2024-03-18 11:21 UTC, ptrvsrg commented on elasticsearch/config.yml
> +cluster.name: "elk"
Давай более развёрнутое имя дадим, например, `archipio-elasticsearch-cluster`

2024-03-18 11:21 UTC, ptrvsrg commented on kibana/config.yml
> +server.name: kibana
Аналогично, давай дадим более развернутое имя

2024-03-18 11:21 UTC, ptrvsrg commented on kibana/config.yml
> +elasticsearch.username: ADMIN_NAME
Мне кажется переменные среды задаются в формате ${ADMIN_NAME}

2024-03-18 11:21 UTC, ptrvsrg commented on kibana/config.yml
> +server.publicBaseUrl: "http://localhost:5601"
Публичный домен будет `https://kibana.archipio.ru`

2024-03-18 11:21 UTC, ptrvsrg commented on logstash/pipelines/service_stamped_json_logs.conf
> +    user => ADMIN_NAME
Аналогично с неймингом переменной среды

2024-03-18 11:21 UTC, ptrvsrg commented on sample.env
> +ADMIN_NAME=
Давай зададим более развёрнутые имена переменных среды, чтобы они не затерялись на хосте. Например, ARCHIPIO_ELASTICSEARCH_ADMIN

2024-03-19 18:48 UTC, ptrvsrg commented on docker-compose.yml
> +  kibana:
Пробрось порт UI

2024-03-19 18:48 UTC, ptrvsrg approved these changes

2024-03-19 18:55 UTC, ptrvsrg commented
# Логи elasticsearch
```shell
{"type": "server", "timestamp": "2024-03-19T18:45:20,384Z", "level": "ERROR", "component": "o.e.i.g.GeoIpDownloader", "cluster.name": "archipio-elasticsearch-cluster", "node.name": "56930a62773f", "message": "exception during geoip databases update", "cluster.uuid": "4aCqzlLIRau5rtoAQgGStg", "node.id": "EiIS6urPQ7qlXXPKI4SyTw" , 
2024-03-19T18:45:20.395198124Z "stacktrace": ["java.net.SocketTimeoutException: Read timed out",
2024-03-19T18:45:20.395205314Z "at sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283) ~[?:?]",
2024-03-19T18:45:20.395211404Z "at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309) ~[?:?]",
2024-03-19T18:45:20.395217274Z "at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350) ~[?:?]",
2024-03-19T18:45:20.395222564Z "at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803) ~[?:?]",
2024-03-19T18:45:20.395227984Z "at java.net.Socket$SocketInputStream.read(Socket.java:966) ~[?:?]",
2024-03-19T18:45:20.395233624Z "at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478) ~[?:?]",
2024-03-19T18:45:20.395238644Z "at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472) ~[?:?]",
2024-03-19T18:45:20.395268834Z "at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160) ~[?:?]",
2024-03-19T18:45:20.395274594Z "at sun.security.ssl.SSLTransport.decode(SSLTransport.java:111) ~[?:?]",
2024-03-19T18:45:20.395279634Z "at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500) ~[?:?]",
2024-03-19T18:45:20.395284764Z "at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415) ~[?:?]",
2024-03-19T18:45:20.395290184Z "at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450) ~[?:?]",
2024-03-19T18:45:20.395295514Z "at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421) ~[?:?]",
2024-03-19T18:45:20.395300724Z "at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580) ~[?:?]",
2024-03-19T18:45:20.395306214Z "at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183) ~[?:?]",
2024-03-19T18:45:20.395311644Z "at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[?:?]",
2024-03-19T18:45:20.395316904Z "at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]",
2024-03-19T18:45:20.395322204Z "at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529) ~[?:?]",
2024-03-19T18:45:20.395327274Z "at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308) ~[?:?]",
2024-03-19T18:45:20.395334494Z "at org.elasticsearch.ingest.geoip.HttpClient.lambda$get$0(HttpClient.java:55) ~[ingest-geoip-7.16.1.jar:7.16.1]",
2024-03-19T18:45:20.395340104Z "at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]",
2024-03-19T18:45:20.395345784Z "at org.elasticsearch.ingest.geoip.HttpClient.doPrivileged(HttpClient.java:97) ~[ingest-geoip-7.16.1.jar:7.16.1]",
2024-03-19T18:45:20.395351264Z "at org.elasticsearch.ingest.geoip.HttpClient.get(HttpClient.java:49) ~[ingest-geoip-7.16.1.jar:7.16.1]",
2024-03-19T18:45:20.395356504Z "at org.elasticsearch.ingest.geoip.HttpClient.getBytes(HttpClient.java:40) ~[ingest-geoip-7.16.1.jar:7.16.1]",
2024-03-19T18:45:20.395361914Z "at org.elasticsearch.ingest.geoip.GeoIpDownloader.fetchDatabasesOverview(GeoIpDownloader.java:135) ~[ingest-geoip-7.16.1.jar:7.16.1]",
2024-03-19T18:45:20.395367784Z "at org.elasticsearch.ingest.geoip.GeoIpDownloader.updateDatabases(GeoIpDownloader.java:123) ~[ingest-geoip-7.16.1.jar:7.16.1]",
2024-03-19T18:45:20.395373194Z "at org.elasticsearch.ingest.geoip.GeoIpDownloader.runDownloader(GeoIpDownloader.java:260) [ingest-geoip-7.16.1.jar:7.16.1]",
2024-03-19T18:45:20.395378474Z "at org.elasticsearch.ingest.geoip.GeoIpDownloaderTaskExecutor.nodeOperation(GeoIpDownloaderTaskExecutor.java:97) [ingest-geoip-7.16.1.jar:7.16.1]",
2024-03-19T18:45:20.395384104Z "at org.elasticsearch.ingest.geoip.GeoIpDownloaderTaskExecutor.nodeOperation(GeoIpDownloaderTaskExecutor.java:43) [ingest-geoip-7.16.1.jar:7.16.1]",
2024-03-19T18:45:20.395389604Z "at org.elasticsearch.persistent.NodePersistentTasksExecutor$1.doRun(NodePersistentTasksExecutor.java:42) [elasticsearch-7.16.1.jar:7.16.1]",
2024-03-19T18:45:20.395402594Z "at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:777) [elasticsearch-7.16.1.jar:7.16.1]",
2024-03-19T18:45:20.395408344Z "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.16.1.jar:7.16.1]",
2024-03-19T18:45:20.395413774Z "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]",
2024-03-19T18:45:20.395419044Z "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]",
2024-03-19T18:45:20.395424494Z "at java.lang.Thread.run(Thread.java:833) [?:?]"] }
```

# Логи kibana

```shell
{"type":"log","@timestamp":"2024-03-19T18:45:11+00:00","tags":["error","elasticsearch-service"],"pid":7,"message":"Unable to retrieve version information from Elasticsearch nodes. security_exception: [security_exception] Reason: unable to authenticate user [${ARCHIPIO_ELASTICSEARCH_ADMIN] for REST request [/_nodes?filter_path=nodes.*.version%2Cnodes.*.http.publish_address%2Cnodes.*.ip]"}
```

# UI kibana

![image](https://github.com/archip-io/deployment/assets/90527574/cc92ab80-75fb-4863-ae1f-193bf66d0324)

2024-03-19 19:03 UTC, ptrvsrg requested changes

2024-03-19 19:03 UTC, ptrvsrg commented on logstash/pipelines/service_stamped_json_logs.conf
> +    user => ${ARCHIPIO_ELASTICSEARCH_ADMIN:-elasticsearchadmin}
Есть подозрения, что в logstash в другом формате переменные среды принимает. Но я не уверен

2024-03-20 11:27 UTC, ptrvsrg requested changes

2024-03-20 11:27 UTC, ptrvsrg commented on docker-compose.yml
> +      - archipio-elasticsearch-data:${ARCHIPIO_ELASTICSEARCH_PATH_DATA:-/usr/share/elasticsearch/data}
Кажется, что такая переменная среды не нужна, потому что elastic хранит данные в определённом несменяемом месте

2024-03-20 11:27 UTC, ptrvsrg commented on docker-compose.yml
> +      - "5601:5601"
Замени ещё порт, на который пробрасываем переменной среды, например, ARCHIPIO_KIBANA_PORT (ни и дефолтное значение добавь), чтобы при развёртывании можно было указать порт, если вдруг 5601 занят

2024-03-20 11:27 UTC, ptrvsrg commented on elasticsearch/elasticsearch.yml
> +path.data: ${ARCHIPIO_ELASTICSEARCH_PATH_DATA:-/usr/share/elasticsearch/data}
давай избавимся, пусть хранит в дефолтном месте

2024-03-20 11:27 UTC, ptrvsrg commented on kibana/kibana.yml
> +elasticsearch.hosts: [ "http://elasticsearch:9200" ]
контейнер с elasticsearch называется archipio-elasticsearch. В docker сетях названия контейнеров можно сказать являются DNS-доменами

2024-03-20 11:27 UTC, ptrvsrg commented on logstash/pipelines/service_stamped_json_logs.conf
> +    hosts    => "https://localhost:9200"
Давай тоже через DNS и http

2024-03-20 11:27 UTC, ptrvsrg commented on logstash/pipelines/service_stamped_json_logs.conf
> +    user => ${ARCHIPIO_ELASTICSEARCH_ADMIN:-elasticsearchadmin}
Либо подчисти дефолтное значение, либо [здесь](https://www.elastic.co/guide/en/logstash/current/environment-variables.html) описано использование переменных среды

2024-03-20 11:27 UTC, ptrvsrg commented on sample.env
> +ARCHIPIO_ELASTICSEARCH_PATH_DATA=
Получается, не нужно

2024-03-27 09:06 UTC, ptrvsrg requested changes

2024-03-27 09:06 UTC, ptrvsrg commented on docker-compose.yml
> +      - ./elasticsearch/data:/usr/share/elasticsearch/data
Сделай именованный volume
./elasticsearch/data -> archipio_elasticsearch_data

2024-03-27 09:06 UTC, ptrvsrg commented on docker-compose.yml
> +    depends_on:
сделай зависимость от healthcheck как в kibana

2024-03-27 09:18 UTC, ptrvsrg requested changes

2024-03-27 09:18 UTC, ptrvsrg commented on docker-compose.yml
> +      - ${ARCHIPIO_KIBANA_PORT:-5601:5601}
${ARCHIPIO_KIBANA_PORT:-5601}:5601

2024-03-27 09:19 UTC, antuanviolin commented on docker-compose.yml
> +      - ./elasticsearch/data:/usr/share/elasticsearch/data
так ты же прошлом патче говорил убрать

2024-03-27 11:19 UTC, ptrvsrg approved these changes

2024-03-27 11:19 UTC, merged